import { normalizeRemision } from '@/lib/inventory/arkikEntriesComparator';

const SKIP_REFERENCE_TYPES = new Set(['inventory_closure']);

/** Reference types generated by system flows, not supplier remisiones. */
export function isSkippableAdjustmentReferenceType(referenceType: string | null | undefined): boolean {
  const rt = referenceType?.trim() ?? '';
  if (!rt) return false;
  if (SKIP_REFERENCE_TYPES.has(rt)) return true;
  if (rt.endsWith('_opening')) return true;
  return false;
}

/**
 * Best-effort remisión key for a positive material adjustment (reference_type, then reference_notes).
 */
export function extractAdjustmentRemision(
  referenceType: string | null | undefined,
  referenceNotes: string | null | undefined
): string | null {
  if (isSkippableAdjustmentReferenceType(referenceType)) return null;

  const rt = referenceType?.trim();
  if (rt) {
    const fromType = normalizeRemision(rt);
    if (fromType) return fromType;
  }

  const notes = referenceNotes?.trim() ?? '';
  if (!notes) return null;

  const labeled = /remisi[oó]n\s*[:#]?\s*([0-9A-Za-z-]+)/i.exec(notes);
  if (labeled?.[1]) {
    return normalizeRemision(labeled[1]);
  }

  if (notes.length <= 40 && /^[0-9A-Za-z-]+$/.test(notes)) {
    return normalizeRemision(notes);
  }

  const digitRun = /\b(\d{4,})\b/.exec(notes);
  if (digitRun?.[1]) {
    return normalizeRemision(digitRun[1]);
  }

  return null;
}
