import { StyleSheet } from '@react-pdf/renderer'
import { DC_DOCUMENT_THEME, DC_DOCUMENT_TYPOGRAPHY } from '@/lib/reports/branding'

const T = DC_DOCUMENT_THEME
const TY = DC_DOCUMENT_TYPOGRAPHY

export const verificacionPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 44,
    paddingHorizontal: 28,
    fontSize: TY.sizeBody,
    fontFamily: TY.fontFamilyBody,
    color: T.textPrimary,
  },
  header: {
    flexDirection: 'row',
    marginBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: T.navy,
    paddingBottom: 8,
  },
  logo: { width: 64, height: 32, objectFit: 'contain', marginRight: 10 },
  headerText: { flex: 1 },
  docTitle: { fontSize: TY.sizeH1, fontWeight: 'bold', color: T.navy },
  docSubtitle: { fontSize: TY.sizeFooter, color: T.textMuted, marginTop: 2 },
  normaBand: {
    backgroundColor: T.green,
    color: T.white,
    fontSize: TY.sizeFooter,
    textAlign: 'center',
    paddingVertical: 4,
    marginBottom: 8,
  },
  templateDesc: {
    fontSize: TY.sizeFooter,
    color: T.textSecondary,
    marginBottom: 8,
    padding: 6,
    backgroundColor: T.surfaceSubtle,
    borderWidth: 1,
    borderColor: T.borderLight,
  },
  metaGrid: {
    borderWidth: 1,
    borderColor: T.borderMedium,
    marginBottom: 8,
  },
  metaRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: T.borderLight },
  metaLabel: {
    width: '34%',
    backgroundColor: T.navy,
    color: T.white,
    fontSize: TY.sizeFooter,
    fontWeight: 'bold',
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  metaValue: {
    width: '66%',
    fontSize: TY.sizeFooter,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  notesBox: {
    fontSize: TY.sizeFooter,
    color: T.textSecondary,
    marginBottom: 8,
    padding: 6,
    borderWidth: 1,
    borderColor: T.borderLight,
    backgroundColor: T.surfacePanel,
  },
  sectionTitle: {
    backgroundColor: T.navy,
    color: T.white,
    fontSize: TY.sizeTable,
    fontWeight: 'bold',
    paddingVertical: 4,
    paddingHorizontal: 6,
    marginTop: 6,
  },
  sectionDesc: {
    fontSize: TY.sizeFooter,
    color: T.textMuted,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: T.borderLight,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: T.greenDark,
    borderBottomWidth: 1,
    borderBottomColor: T.borderMedium,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: T.borderLight,
    minHeight: 16,
  },
  tableRowAlt: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: T.borderLight,
    backgroundColor: T.rowAlternate,
    minHeight: 16,
  },
  th: {
    fontSize: 7,
    fontWeight: 'bold',
    color: T.white,
    paddingVertical: 3,
    paddingHorizontal: 3,
    flexGrow: 1,
    flexBasis: 0,
  },
  td: {
    fontSize: 7,
    paddingVertical: 3,
    paddingHorizontal: 3,
    flexGrow: 1,
    flexBasis: 0,
    color: T.textPrimary,
  },
  tdMono: {
    fontSize: 7,
    paddingVertical: 3,
    paddingHorizontal: 3,
    flexGrow: 1,
    flexBasis: 0,
    fontFamily: TY.fontFamilyMono,
  },
  tdCumple: {
    fontSize: 7,
    paddingVertical: 3,
    paddingHorizontal: 3,
    width: 48,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  coverTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: T.navy,
    textAlign: 'center',
    marginBottom: 12,
  },
  coverMeta: { fontSize: TY.sizeBody, marginBottom: 4, color: T.textSecondary },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 28,
    right: 28,
    fontSize: 7,
    color: T.textMuted,
    borderTopWidth: 1,
    borderTopColor: T.footerRule,
    paddingTop: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fichaSeparator: {
    marginTop: 4,
    marginBottom: 4,
    borderTopWidth: 1,
    borderTopColor: T.borderMedium,
  },
})
