import { StyleSheet } from '@react-pdf/renderer'
import { DC_DOCUMENT_THEME, DC_DOCUMENT_TYPOGRAPHY } from '@/lib/reports/branding'

const T = DC_DOCUMENT_THEME
const TY = DC_DOCUMENT_TYPOGRAPHY

export const verificacionPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 48,
    paddingHorizontal: 32,
    fontSize: TY.sizeBody,
    fontFamily: TY.fontFamilyBody,
    color: T.textPrimary,
  },
  pageLandscape: {
    paddingTop: 28,
    paddingBottom: 40,
    paddingHorizontal: 24,
    fontSize: TY.sizeBody,
    fontFamily: TY.fontFamilyBody,
    color: T.textPrimary,
  },
  summaryStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 8,
    backgroundColor: T.surfaceSubtle,
    borderWidth: 1,
    borderColor: T.borderLight,
    marginBottom: 8,
  },
  summaryItem: {
    fontSize: 7.5,
    color: T.textPrimary,
    marginRight: 10,
  },
  header: {
    flexDirection: 'row',
    marginBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: T.navy,
    paddingBottom: 10,
  },
  logo: { width: 72, height: 36, objectFit: 'contain', marginRight: 12 },
  headerText: { flex: 1 },
  docTitle: { fontSize: 13, fontWeight: 'bold', color: T.navy, letterSpacing: 0.3 },
  docSubtitle: { fontSize: 8, color: T.textMuted, marginTop: 3, lineHeight: 1.35 },
  docCode: {
    fontSize: 8,
    color: T.navy,
    fontFamily: TY.fontFamilyMono,
    marginTop: 4,
  },
  card: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: T.borderMedium,
  },
  cardHeader: {
    backgroundColor: T.navy,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  cardHeaderText: {
    color: T.white,
    fontSize: 8.5,
    fontWeight: 'bold',
  },
  cardBody: {
    padding: 8,
    backgroundColor: T.surfacePage,
  },
  kvRow: {
    flexDirection: 'row',
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: T.borderLight,
    paddingBottom: 4,
  },
  kvLabel: {
    width: '38%',
    fontSize: 8,
    color: T.textMuted,
    fontWeight: 'bold',
  },
  kvValue: {
    width: '62%',
    fontSize: 8,
    color: T.textPrimary,
  },
  kvValueMono: {
    width: '62%',
    fontSize: 8,
    fontFamily: TY.fontFamilyMono,
    color: T.textPrimary,
  },
  normaBand: {
    backgroundColor: T.green,
    color: T.white,
    fontSize: 8,
    textAlign: 'center',
    paddingVertical: 5,
    marginBottom: 10,
    fontWeight: 'bold',
  },
  procedureTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    color: T.navy,
    textAlign: 'center',
    marginBottom: 6,
  },
  procedureDesc: {
    fontSize: 8,
    color: T.textSecondary,
    marginBottom: 10,
    padding: 8,
    backgroundColor: T.surfaceSubtle,
    borderWidth: 1,
    borderColor: T.borderLight,
    lineHeight: 1.4,
  },
  dictamenBox: {
    marginTop: 8,
    padding: 10,
    borderWidth: 2,
    borderColor: T.navy,
    backgroundColor: T.surfaceSubtle,
    alignItems: 'center',
  },
  dictamenLabel: { fontSize: 8, color: T.textMuted, marginBottom: 4 },
  dictamenValue: { fontSize: 14, fontWeight: 'bold', color: T.navy },
  legalBlock: {
    marginTop: 8,
    padding: 8,
    backgroundColor: T.surfacePanel,
    borderWidth: 1,
    borderColor: T.borderLight,
  },
  legalText: { fontSize: 6.5, color: T.textSecondary, lineHeight: 1.45, marginBottom: 3 },
  sectionBlockTitle: {
    fontSize: 8,
    fontWeight: 'bold',
    color: T.navy,
    marginTop: 6,
    marginBottom: 4,
  },
  sectionBlockDesc: {
    fontSize: 7,
    color: T.textMuted,
    marginBottom: 4,
    lineHeight: 1.35,
  },
  tableFrame: {
    borderWidth: 1,
    borderColor: T.borderMedium,
    marginTop: 2,
    marginBottom: 6,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: T.greenDark,
  },
  tableHeaderText: {
    color: T.white,
    fontWeight: 'bold',
    lineHeight: 1.25,
  },
  tableBodyRow: {
    flexDirection: 'row',
    backgroundColor: T.white,
    minHeight: 18,
  },
  tableBodyRowAlt: {
    flexDirection: 'row',
    backgroundColor: T.rowAlternate,
    minHeight: 18,
  },
  tableCell: {
    paddingVertical: 4,
    paddingHorizontal: 4,
    justifyContent: 'center',
  },
  tableCellText: {
    color: T.textPrimary,
    lineHeight: 1.25,
  },
  tableCellMono: {
    fontFamily: TY.fontFamilyMono,
    color: T.textPrimary,
    lineHeight: 1.25,
  },
  coverTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: T.navy,
    marginTop: 8,
    marginBottom: 8,
  },
  coverMeta: { fontSize: 9, marginBottom: 5, color: T.textSecondary },
  signatureRow: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 16,
  },
  signatureBox: {
    flex: 1,
    borderTopWidth: 1,
    borderTopColor: T.borderStrong,
    paddingTop: 6,
    minHeight: 48,
  },
  signatureLabel: { fontSize: 7, color: T.textMuted, marginBottom: 20 },
  signatureName: { fontSize: 8, fontWeight: 'bold' },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 32,
    right: 32,
    fontSize: 7,
    color: T.textMuted,
    borderTopWidth: 1,
    borderTopColor: T.footerRule,
    paddingTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
})
