export const EMA_VERIFICACION_WRITE_ROLES = [
  'QUALITY_TEAM',
  'LABORATORY',
  'PLANT_MANAGER',
  'EXECUTIVE',
  'ADMIN',
] as const

export const EMA_VERIFICACION_READ_ROLES = [
  ...EMA_VERIFICACION_WRITE_ROLES,
  'ADMIN_OPERATIONS',
] as const
